import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import AuthProvider from "./context/AuthProvider";
import AuthButtons from "@/components/AuthButtons/AuthButtons";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "StyleHub",
  description: "Generated by StyleHub",
};

export default function RootLayout({ children }) {
  const navItem = (
    <>
      <li>
        <Link href="/products">Products</Link>
      </li>
      <li>
        <Link href="/dashboard/add-product">Add Product</Link>
      </li>
    </>
  );
  const authButton = <>
    <AuthButtons/>
  </>
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
        <header className="bg-base-100 shadow-sm px-3 lg:px-0">
          <div className="navbar max-w-7xl mx-auto p-0">
            <div className="navbar-start">
              <div className="dropdown">
                <div
                  tabIndex={0}
                  role="button"
                  className="btn btn-ghost lg:hidden"
                >
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    className="h-5 w-5"
                    fill="none"
                    viewBox="0 0 24 24"
                    stroke="currentColor"
                  >
                    {" "}
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      strokeWidth="2"
                      d="M4 6h16M4 12h8m-8 6h16"
                    />{" "}
                  </svg>
                </div>
                <ul
                  tabIndex={0}
                  className="menu menu-sm dropdown-content bg-base-100 rounded-box z-1 mt-3 w-52 p-2 shadow gap-3"
                >
                  {navItem}
                  {authButton}
                </ul>
              </div>
              <Link href="/" className="text-2xl font-bold cursor-pointer">
                StyleHub
              </Link>
            </div>
            <div className="navbar-center hidden lg:flex">
              <ul className="menu menu-horizontal px-1">{navItem}</ul>
            </div>
            <div className="navbar-end gap-4 hidden md:flex">{authButton}</div>
          </div>
        </header>
        <main className="max-w-7xl mx-auto px-3 lg:px-0 min-h-screen">{children}</main>
        <footer className="bg-slate-800 text-slate-400 mt-40">
          <div className="container mx-auto px-6 py-8 text-center">
            <p>© 2024 StyleHub. All rights reserved.</p>
          </div>
        </footer>
        </AuthProvider>
      </body>
    </html>
  );
}
